# Generated by Django 4.2.4 on 2024-01-27 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="description",
        ),
    ]
