# Generated by Django 4.2.4 on 2024-01-27 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0002_remove_data_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="name",
            new_name="direction",
        ),
    ]
