# Generated by Django 4.2.4 on 2024-01-27 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0003_rename_name_data_direction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="direction",
            new_name="name",
        ),
        migrations.AddField(
            model_name="data",
            name="lives",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(242),
                ],
            ),
        ),
    ]
