# Generated by Django 4.2.4 on 2024-01-27 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0004_rename_direction_data_name_data_lives_data_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="lives",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
