# Generated by Django 4.2.4 on 2024-01-27 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0005_alter_data_lives"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="lives",
            new_name="hearts",
        ),
    ]
