# Generated by Django 4.2.4 on 2024-01-27 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0006_rename_lives_data_hearts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="hearts",
        ),
        migrations.AddField(
            model_name="data",
            name="heart",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
