# Generated by Django 4.2.4 on 2024-01-27 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0007_remove_data_hearts_data_heart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="heart",
            new_name="num_lives",
        ),
    ]
